on:
  release:
    types: [published]
concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  quality_artifacts_job:
    name: A job to collect quality artifacts
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show release URL
        run: |
          echo ${{ github.event.release.html_url }}
      # Do the quality artifact collection thing
      - name: Collect quality artifacts
        uses: eclipse-dash/quevee@v1
        id: quevee
        with:
          release_url: ${{ github.event.release.html_url }}
          artifacts_readme: README.md
          artifacts_requirements: docs/requirements.md
          artifacts_testing: tests/file_1
          artifacts_documentation: 
          artifacts_coding_guidelines: docs/coding_guidelines.md
          artifacts_release_process: https://example.org/my_release_process/
      - name: Upload quality manifest to release
        uses: svenstaro/upload-release-action@v2
        id: upload_manifest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.quevee.outputs.manifest_file }}
          tag: ${{ github.ref }}  